package com.spring.security.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;

@Entity
@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UserCredential {
    @Id // primary key annotation of @Entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // id value will be autogenerated
    private int id; // primary key of the UserCredential class
    private String name;
    private String email;
    private String password;

}
